version: "3"

services:

  postgres:
    image: "library/postgres:9.6.6"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - redmine
    volumes:
      - "redmine-db:/var/lib/postgresql/data"

  redmine:
    image: "library/redmine:3.4.4"
    networks:
      - redmine
    volumes:
      - "./config/configuration.yml:/usr/src/redmine/config/configuration.yml:ro"
      - "./config/database.yml:/usr/src/redmine/config/database.yml:ro"
      - "./config/additional_environment.rb:/usr/src/redmine/config/additional_environment.rb:ro"
      - "redmine-files:/usr/src/redmine/files"

  redmine-email:
    build: ./redmine-email/
    networks:
      - redmine
    volumes:
      - "./config/configuration.yml:/usr/src/redmine/config/configuration.yml:ro"
      - "./config/database.yml:/usr/src/redmine/config/database.yml:ro"
      - "./config/additional_environment.rb:/usr/src/redmine/config/additional_environment.rb:ro"
      - "redmine-files:/usr/src/redmine/files"

  nginx:
    build: ./nginx-forwardproxy/
    environment:
      HTTPSPORT: 3443
      DOMAINNAME: idr0-slot3.openmicroscopy.org
      BACKENDS: "/|http://redmine:3000"
    networks:
      - redmine
    ports:
      - "3443:3443"

networks:
  redmine:

volumes:
  redmine-db:
  redmine-files:
