apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: idr-redmine
  labels:
    app: idr-redmine
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: idr-redmine
          servicePort: 80
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
