apiVersion: v1
kind: PersistentVolume
metadata:
  name: idr-redmine-nfs
  labels:
    app: idr-redmine
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: idr-data.openmicroscopy.org
    path: /uod/idr/k8s-volumes/idr-redmine
